version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./auth_test_proj:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db
    entrypoint: >
      bash -c "
      echo 'Waiting for db...';
      while ! pg_isready -h db -p 5432 -U postgres; do
        sleep 2;
        echo 'Waiting for db...';
      done;
      echo 'Database is ready, running migrations...';
      npm install;
      npm run build;
      rm -rf node_modules/.vite;
      ls -l /var/www/html/public/build;
      chmod -R 777 storage/framework/sessions;
      chown -R www-data:www-data storage/framework/sessions;
      chown -R www-data:www-data storage/framework/cache;
      chown -R www-data:www-data storage/framework/cache/data;
      php artisan migrate:reset --force;
      php artisan migrate --force;
      php artisan db:seed;
      php artisan test;
      php-fpm
      "

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./auth_test_proj:/var/www/html
    depends_on:
      - app

volumes:
  db-data:
